networks:
  consort-network:
    name: consort-infra_consort-network
    driver: bridge

volumes:
  postgres_data:
  redis_user_data:
  redis_logging_data:
  redis_notification_data:
  redis_course_data:
  redis_forum_data:
  redis_webinar_data:
  redis_support_data:
  redis_certificate_data:
  kafka_data:

services:
  db:
    image: postgres:15
    container_name: consort-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - consort-network

    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: bitnami/kafka:3.7.0
    container_name: consort-kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_CLUSTER_ID}
      - KAFKA_CFG_NODE_ID=1
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - consort-network

    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-user-service:
    image: redis:7.2
    container_name: consort-redis-user-service
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6381:6379"
    volumes:
      - redis_user_data:/data
    networks:
      - consort-network

  redis-logging-service:
    image: redis:7.2
    container_name: consort-redis-logging-service
    restart: unless-stopped
    command: redis-server --save 300 10 --loglevel warning
    ports:
      - "6382:6379"
    volumes:
      - redis_logging_data:/data
    networks:
      - consort-network

  redis-notification-service:
    image: redis:7.2
    container_name: consort-redis-notification-service
    restart: unless-stopped
    command: redis-server --save 300 10 --loglevel warning
    ports:
      - "6383:6379"
    volumes:
      - redis_notification_data:/data
    networks:
      - consort-network

  redis-course-service:
    image: redis:7.2
    container_name: consort-redis-course-service
    restart: unless-stopped
    command: redis-server --save 300 10 --loglevel warning
    ports:
      - "6384:6379"
    volumes:
      - redis_course_data:/data
    networks:
      - consort-network

  redis-forum-service:
    image: redis:7.2
    container_name: consort-redis-forum-service
    restart: unless-stopped
    command: redis-server --save 300 10 --loglevel warning
    ports:
      - "6385:6379"
    volumes:
      - redis_forum_data:/data
    networks:
      - consort-network

  redis-webinar-service:
    image: redis:7.2
    container_name: consort-redis-webinar-service
    restart: unless-stopped
    command: redis-server --save 300 10 --loglevel warning
    ports:
      - "6386:6379"
    volumes:
      - redis_webinar_data:/data
    networks:
      - consort-network

  redis-support-service:
    image: redis:7.2
    container_name: consort-redis-support-service
    restart: unless-stopped
    command: redis-server --save 300 10 --loglevel warning
    ports:
      - "6387:6379"
    volumes:
      - redis_support_data:/data
    networks:
      - consort-network

  redis-certificate-service:
    image: redis:7.2
    container_name: consort-redis-certificate-service
    restart: unless-stopped
    command: redis-server --save 300 10 --loglevel warning
    ports:
      - "6388:6379"
    volumes:
      - redis_certificate_data:/data
    networks:
      - consort-network

  eureka-service:
    build:
      context: ../eureka_service
      dockerfile: Dockerfile
    container_name: consort-eureka-service
    restart: unless-stopped
    ports:
      - "8761:8762"
    networks:
      consort-network:
        aliases:
          - eureka-service
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8762/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway-service:
    build:
      context: ../api_gateway_service
      dockerfile: Dockerfile
    container_name: consort-api-gateway-service
    env_file:
      - .env
    depends_on:
      eureka-service:
        condition: service_healthy
    entrypoint:
      - /bin/sh
      - -c
      - |
        sleep 20 && java -Dsun.net.inetaddr.ttl=0 -jar app.jar
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_CLOUD_EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://localhost:8761/eureka/
    ports:
      - "8080:8085"
    networks:
      - consort-network
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8085/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

